[package]
name = "seguranca_de_sistema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256 = "1.5.0"
digest = "0.11.0-pre.8"
hex = "0.4.3"
rand = { version = "0.9.0-alpha.0"}
